# Introducción {.unnumbered}

En Colombia, para estar a la vanguardia en el avance tecnológico y científico, diferentes instituciones y sectores han desarrollado mecanismos para el manejo de datos geoespaciales a nivel nacional que optimizan la planificación, el manejo y el control de datos. Las instituciones encargadas de generar datos e información de la gestión del riesgo de desastres en el territorio, no son la excepción. Estas herramientas se enmarcan en la normatividad vigente, en particular en la Ley 1523 de 2012, por la cual se adopta la política nacional de gestión del riesgo de desastres y se establece el Sistema Nacional de Gestión del Riesgo de Desastres. 

Esta ley, en el Capítulo IV de Sistemas de Información, dispone la creación del* Sistema Nacional de Información para Gestión del Riesgo de Desastres*, el cual debe mantenerse actualizado y funcional mediante la integración de contenidos de todas las entidades nacionales y territoriales. Asimismo, establece que las autoridades departamentales, distritales y municipales deben crear sistemas de información para la gestión del riesgo de desastres en el ámbito de su jurisdicción en armonía con el sistema nacional y garantizando la interoperabilidad de los datos.

En este contexto, los Sistemas de Información Geográfica (SIG) se han consolidado como herramientas fundamentales para apoyar la toma de decisiones y la gestión de la información en todos los aspectos relacionados con la gestión del riesgo de desastres [@nrc2007; @goodchild2010; @esri2020a]. Por este motivo, existen diferentes aplicaciones de SIG que permiten almacenar y gestionar datos, generar mapas y visualizaciones de datos 2D y 3D, realizar análisis espaciales y procesar imágenes de satélites y datos tipo raster y vectoriales. [@cutter2010; @mileti1999]. Como resultado, es posible representar a través de mapas, aspectos clave como la ubicación de emergencias, zonas categorizadas con amenaza alta, poblaciones afectadas, rutas de evacuación, escenarios de riesgo, entre otros.

Con este propósito, la Unidad Nacional para la Gestión del Riesgo de Desastres (UNGRD) presenta este documento para apoyar a las administraciones departamentales y municipales en la implementación de los SIG. El documento reúne conceptos básicos, guías y enlaces de acceso a plataformas y geoportales oficiales para la recopilación y descarga de información. Asimismo, describe la aplicación de los SIG en los tres subprocesos de la Gestión del Riesgo de Desastres (GRD) y presenta ejemplos de mapas e insumos que los territorios podrían considerar como prioritarios. Finalmente, incluye cinco anexos con instrucciones prácticas para la elaboración de mapas básicos en la plataforma de acceso gratuito QGIS, y para el uso de plataformas y herramientas útiles como: Google Earth, MAGNA PRO, Kobo ToolBox y Avenza, contribuyendo de esta manera a la implementación efectiva de los SIG y al fortalecimiento de las capacidades técnicas e institucionales en el territorio.

