project:
  type: book
  output-dir: _book
  resources:
    - Anexo_1_slides.html
    - Anexo_1_slides_files/

book:
  title: "Aplicación de los sistemas de información geográfica (SIG) en la Gestión del Riesgo"
  date: "2026-06-03"
  
  repo-url: https://github.com/scr-ungrd/aplicacion-sig-grd
  repo-actions: [source, issue]
  site-url: https://scr-ungrd.github.io/aplicacion-sig-grd
  favicon: media/favicon.png
  sidebar:
    style: floating
    collapse-level: 1
  chapters:
    - index.qmd
    - Pagina-legal.qmd
    - presentacion.qmd
    - text: "1. Introducción"
      href: 01-introduccion.qmd
    - text: "2. Marco teórico de los SIG"
      href: 02-marco-teorico-de-los-sig.qmd
    - text: "3. Usos y aplicaciones de los SIG"
      href: 03-usos-y-aplicaciones-de-los-sig.qmd
    - text: "4. Fuentes de información"
      href: 04-fuentes-de-informacion.qmd
    - text: "5. SIG aplicado a la gestión del riesgo"
      href: 05-sig-aplicado-a-la-gestion-del-riesgo.qmd
    - text: "6. ¿Cómo realizar un SIG en GRD a nivel municipal?"
      href: 06-como-realizar-un-sig-en-grd-a-nivel-municipal.qmd
    - text: "7. Recomendaciones generales para un SIG en GRD municipal"
      href: 07-recomendaciones-generales-para-un-sig-en-grd-.qmd
    - text: "8. Checklist de seguimiento del SIG municipal para GRD"
      href: 08-checklist-de-seguimiento-del-sig-municipal-pa.qmd
    - text: "9. Insumos de interés"
      href: 09-insumos-de-interes.qmd
    - 10-referencias.qmd
    - part: anexos.qmd
      chapters:
        - Anexo_1_Descarga_Imagenes_Satelitales.qmd
        - Anexo_2_Google_Earth.qmd
        - Anexo_3_Magna_Pro.qmd
        - Anexo_4_KoboToolbox.qmd
        - Anexo_5_Avenza.qmd

lang: es

bibliography: references.bib
csl: apa.csl
link-citations: true
nocite: |
  @*

crossref:
  fig-prefix: "Figura"
  tbl-prefix: "Tabla"
  chapters: true

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    reference-location: block
    logo: media/CUB_MARCO TEORICO SIG-1.png
    css:
      - custom.css
    include-in-header:
      - caption-bold.html
      - text: |
          <meta name="citation_book_title" content="Aplicación SIG en la Gestión del Riesgo de Desastres para Colombia.">
          <meta name="citation_publisher" content="Unidad Nacional para la Gestión del Riesgo de Desastres - UNGRD">
          <meta name="citation_publication_date" content="2026/02/03">
          <meta name="citation_online_date" content="2026/02/03">
          <meta name="citation_doi" content="10.5281/zenodo.21518659">
          <meta name="citation_language" content="es">
          <meta name="robots" content="index, follow">
    html-math-method: katex
